apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "stock-api.fullname" . }}
  labels:
    helm.sh/chart: {{ template "stock-api.chart" . }}
    app.kubernetes.io/name: {{ template "stock-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ template "stock-api.name" . }}
spec:
  replicas: {{ .Values.stock_api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "stock-api.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "stock-api.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: {{ template "stock-api.name" . }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/scheme: 'http'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.stock_api.image.repository }}:{{ .Values.stock_api.image.tag }}"
          imagePullPolicy: {{ .Values.stock_api.image.pullPolicy }}
          env:
            - name: REDIS_HOST
              value: "{{ .Values.stock_api.redisHost }}"
          ports:
            - name: http
              containerPort: {{ .Values.stock_api.port }}
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "stock-api.name" . }}
spec:
  selector:
    app: {{ template "stock-api.name" . }}
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8080
